version: '2.4'
services:
  enabled:
    volumes:
    - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:ro
    - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:ro
    - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:ro
    - /var/lib/lxcfs/proc/stat:/proc/stat:ro
    - /var/lib/lxcfs/proc/swaps:/proc/swaps:ro
    - /var/lib/lxcfs/proc/uptime:/proc/uptime:ro
  disabled: {}

